# Generated by Django 4.2.3 on 2023-07-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0002_alter_ciudad_table'),
        ('salas', '0002_alter_asiento_table_alter_sala_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_sala', to='ciudades.ciudad'),
        ),
    ]
