# Generated by Django 4.2.3 on 2023-08-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_alter_sala_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'verbose_name': 'Asiento', 'verbose_name_plural': 'Asientos'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterField(
            model_name='asiento',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_asientos', to='salas.sala'),
        ),
    ]
