# Generated by Django 4.2.3 on 2023-07-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='estado',
            field=models.IntegerField(default=True),
        ),
    ]
