# Generated by Django 4.2.3 on 2023-07-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_pelicula_estado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='horario',
            table='horarios',
        ),
        migrations.AlterModelTable(
            name='pelicula',
            table='peliculas',
        ),
    ]
