# Generated by Django 4.2.3 on 2023-07-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_horario_table_alter_pelicula_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id_pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelicula_horario', to='servicios.pelicula'),
        ),
    ]
