# Generated by Django 4.2.3 on 2023-07-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_alter_sala_ciudad'),
        ('servicios', '0004_alter_horario_id_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_horario', to='salas.sala'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
