# Generated by Django 4.2.3 on 2023-07-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_horario_id_sala_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='hora_fin',
        ),
    ]
