# Generated by Django 4.2.3 on 2023-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_horario_options_alter_pelicula_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.FloatField(default=100.0),
        ),
    ]
