# Generated by Django 4.2.3 on 2023-07-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudades',
        ),
    ]
