# Generated by Django 4.2.3 on 2023-08-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0002_alter_ciudad_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
