# Generated by Django 4.2.3 on 2023-08-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleboleto',
            options={'verbose_name': 'Detalle de Boleto', 'verbose_name_plural': 'Detalles de Boletos'},
        ),
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'verbose_name': 'Detalle de Producto', 'verbose_name_plural': 'Detalles de Productos'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
