# Generated by Django 4.2.3 on 2023-08-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_pelicula_precio'),
        ('transacciones', '0002_alter_detalleboleto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleboleto',
            name='id_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_detalle', to='servicios.horario'),
        ),
    ]
