# Generated by Django 4.2.3 on 2023-08-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_detalleboleto_id_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleboleto',
            name='precio_unitario',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
