# Generated by Django 4.2.3 on 2023-07-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clientes',
            managers=[
            ],
        ),
    ]
