# Generated by Django 4.2.3 on 2023-07-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={},
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
    ]
