# Generated by Django 4.2.3 on 2023-07-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_clientes_first_name_alter_clientes_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='DNI',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='FechaNac',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
