# Generated by Django 4.2.3 on 2023-07-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_clientes_dni_alter_clientes_fechanac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
