# Generated by Django 4.2.3 on 2023-08-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_codigoverificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='codigoverificacion',
            options={'verbose_name': 'Codigo de Verificacion', 'verbose_name_plural': 'Codigos de Verificacion'},
        ),
        migrations.AlterModelTable(
            name='codigoverificacion',
            table='codigo_verificacion',
        ),
    ]
